(() => {
  const mount = document.getElementById('mirror-activity-mount');
  if (!mount) return;
  const title = window.MIRROR_ACTIVITY?.title || 'Theory';
  mount.innerHTML = `
    <section class="mirror-activity-section" id="knowledge-checks" aria-labelledby="knowledge-checks-title"><div class="mirror-activity-heading"><div><p class="eyebrow">Guided practice</p><h2 id="knowledge-checks-title">${title} knowledge checks</h2><p>Choose an answer, use the feedback, then try again if needed. The hints become more specific after an incorrect attempt.</p></div><div class="mirror-progress-ring" aria-label="Knowledge check progress"><strong id="mc-progress-number">0/3</strong><span>mastered</span></div></div><div class="mirror-question-list" id="mc-questions"></div></section>
    <section class="mirror-activity-section" id="written-application" aria-labelledby="written-application-title"><div class="mirror-activity-heading"><div><p class="eyebrow">Apply your learning</p><h2 id="written-application-title">Guided written response</h2><p>Use the sentence starters, make a short attempt, then use the guidance and model response to improve your own work.</p></div><div class="mirror-progress-ring written" aria-label="Written response progress"><strong id="written-progress-number">0/1</strong><span>reviewed</span></div></div><div class="mirror-written-list" id="written-questions"></div></section>
    <section class="mirror-completion-card" aria-labelledby="completion-title"><div><p class="eyebrow">Finish this theory topic</p><h2 id="completion-title">Save your evidence</h2><p>Your answers save in this browser while you work. Download a PDF before moving devices or clearing browser data, then upload it when your teacher asks.</p></div><div class="mirror-completion-summary" aria-live="polite"><div><span>Knowledge checks</span><strong id="summary-mc">0/3</strong></div><div><span>Written response reviewed</span><strong id="summary-written">0/1</strong></div><div><span>Student details</span><strong id="summary-details">Incomplete</strong></div></div><div class="mirror-student-fields"><label>First name<input id="student-first-name" type="text" autocomplete="given-name"></label><label>Last name<input id="student-last-name" type="text" autocomplete="family-name"></label><label>Class<input id="student-class" type="text" autocomplete="organization"></label></div><div class="mirror-button-row"><button class="mirror-primary-button" id="download-pdf-button" type="button">Download PDF</button><button class="mirror-secondary-button" id="reset-lesson-button" type="button">Reset this topic</button><span id="save-status" aria-live="polite"></span></div><p><a class="text-link" href="mirror_theory_notes.html">Back to Theory Menu</a></p></section>`;
})();
