const MIRROR_FOLIO_STORAGE = 'mirror_folio_session_v2';
const FOLIO_CARDS = [
  ['brief','Project Brief and Success Criteria','Explain what you are making and what a successful timber mirror must achieve.','Project brief, design requirements and personal success criteria.','What are you making, who is it for, and how will you judge whether it is successful?',['The purpose of my timber mirror is to…','My project will be successful if…'],'Function, appearance, strength, accuracy and safety infographic.'],
  ['whs','Work Health and Safety','Show how you worked safely throughout the project.','PPE, safe tool use, workshop rules and identified hazards.','What were the main hazards, and what actions did you take to control them?',['A hazard during this stage was…','I reduced the risk by…'],'Photo of correct PPE or a simple hazard–control diagram.'],
  ['timber','Timber and Cutting List','Record the timber selected and plan the required components.','Timber choice, component names, quantities and cutting list.','Why was this timber suitable, and how did the cutting list help organise your work?',['The timber was suitable because…','The cutting list helped me…'],'Labelled timber photo and cutting-list table.'],
  ['marking','Measuring and Marking','Demonstrate accurate preparation before cutting or machining.','Marked components, reference faces, measurements and tools used.','How did you measure and mark the timber accurately and avoid mistakes?',['I used the ______ to mark…','To improve accuracy, I…'],'Close-up of a square, rule, pencil line or marking gauge.'],
  ['joinery','Joinery','Explain how the frame joints were produced.','Joint type, tools or machines used, cutting stages and completed joints.','How did you make the joints, and what features showed that they fitted correctly?',['The joint was made by…','I knew the joint fitted correctly when…'],'Labelled joint diagram or close-up before assembly.'],
  ['shaping','Shaping and Routing','Record how edges, profiles or decorative details were formed safely.','Profile design, test pieces and finished edges.','What shaping or routing did you complete, and how did you control the quality of the result?',['The profile improved the design by…','Before shaping the final piece, I…'],'Before-and-after edge profile or test-piece photo.'],
  ['assembly','Dry Fit and Assembly','Show how the frame was checked before permanent assembly.','Dry-fit photos, joint checks, diagonal checks, glue-up and clamping method.','What did the dry fit reveal, and how did you assemble the frame accurately?',['During the dry fit, I noticed…','While clamping the frame, I checked…'],'Frame dry fitted or clamped on a flat bench.'],
  ['finishing','Sanding and Finishing','Explain how the surface was prepared and protected.','Sanding sequence, surface preparation, finish used and completed surface.','How did your sanding and finishing process improve the appearance and feel of the frame?',['I prepared the surface by…','The finish changed the timber by…'],'Sanding sequence or before-and-after finish photo.'],
  ['fitting','Mirror, Backing and Hardware Fitting','Record how the mirror and supporting components were fitted safely.','Rebate condition, mirror support, backing, retaining method and hanging hardware.','How were the mirror, backing and hardware fitted without creating movement or pressure points?',['The mirror was supported by…','I checked the hardware by…'],'Cross-section of frame, mirror, backing and retaining system.'],
  ['quality','Quality Checks','Use checks to show that the mirror meets the design brief.','Square corners, even gaps, smooth finish, secure fitting and final appearance.','What checks did you complete, and what did they show about the quality of the mirror?',['I checked the frame by…','This showed that the mirror was…'],'Quality-check list beside the finished mirror.'],
  ['problems','Problems and Solutions','Show how you responded when something did not go to plan.','Problem, likely cause, action taken and result.','What problem occurred, how did you respond, and what would you do differently next time?',['A problem I encountered was…','I solved or reduced this problem by…'],'Problem → action → result infographic.'],
  ['evaluation','Final Evaluation','Judge the completed mirror honestly against the brief and success criteria.','Final photos, strengths, weaknesses and improvements.','How successfully did your timber mirror meet the brief, and what would you improve in a future project?',['The strongest feature of my project is…','If I completed the project again, I would…'],'Final front-and-back photos with labelled strengths and improvements.']
].map(([key,title,purpose,evidence,prompt,starters,visual], index) => ({ id:index + 1, key,title,purpose,evidence,prompt,starters,visual }));

const $ = id => document.getElementById(id);
const cleanName = value => String(value || 'mirror-project-folio').trim().replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'mirror-project-folio';
const setStatus = message => { $('folioStatus').textContent = message; };
const textBytes = text => new TextEncoder().encode(text);
const dataUrlBytes = dataUrl => { const raw = (dataUrl || '').split(',')[1] || ''; const binary = atob(raw); return Uint8Array.from(binary, c => c.charCodeAt(0)); };

function renderCards() {
  $('folioCards').innerHTML = FOLIO_CARDS.map(card => `<article class="folio-card" data-card="${card.key}">
    <div class="folio-number">${card.id}<span>Card</span></div><div class="folio-body">
      <div class="folio-head"><div><p class="eyebrow">Evidence card ${card.id}</p><h2>${card.title}</h2></div><label class="folio-complete"><input type="checkbox" data-done="${card.key}" /> Complete</label></div>
      <div class="folio-meta"><article><h3>Why this matters</h3><p>${card.purpose}</p></article><article><h3>Evidence to collect</h3><p>${card.evidence}</p><h3>Visual idea</h3><p>${card.visual}</p></article></div>
      <div class="folio-response-grid"><div class="folio-field"><label for="response-${card.key}">${card.prompt}</label><textarea id="response-${card.key}" data-response="${card.key}" placeholder="Write your response here…"></textarea></div><div class="folio-field"><label for="note-${card.key}">Evidence note or photo caption</label><textarea id="note-${card.key}" data-note="${card.key}" placeholder="What does your photo, sketch or check prove?"></textarea><details class="sentence-starters"><summary>Sentence starters</summary><ul>${card.starters.map(starter => `<li>${starter}</li>`).join('')}</ul></details></div></div>
      <div class="photo-panel"><h3>Add one useful photo</h3><p>Use your own build photo, sketch or check. It will be included in the ZIP backup.</p><label class="photo-upload">Choose photo<input type="file" accept="image/*" data-photo="${card.key}" /></label><img class="photo-preview" data-preview="${card.key}" alt="${card.title} evidence preview" /></div>
    </div></article>`).join('');
}

function getSession() {
  const responses = {}, notes = {}, done = {}, photos = {};
  FOLIO_CARDS.forEach(card => { responses[card.key] = $(`response-${card.key}`).value; notes[card.key] = $(`note-${card.key}`).value; done[card.key] = document.querySelector(`[data-done="${card.key}"]`).checked; const img = document.querySelector(`[data-preview="${card.key}"]`); if (img.dataset.dataUrl) photos[card.key] = { name:img.dataset.fileName || `${card.key}.jpg`, dataUrl:img.dataset.dataUrl }; });
  return { version:2, project:'Year 10 Timber Mirror Project Folio', savedAt:new Date().toISOString(), student:{ first:$('studentFirst').value, last:$('studentLast').value, className:$('studentClass').value, sessionDate:$('sessionDate').value }, responses, notes, done, photos };
}

function applySession(session) {
  const student = session.student || {}; $('studentFirst').value = student.first || ''; $('studentLast').value = student.last || ''; $('studentClass').value = student.className || ''; $('sessionDate').value = student.sessionDate || '';
  FOLIO_CARDS.forEach(card => { $(`response-${card.key}`).value = session.responses?.[card.key] || ''; $(`note-${card.key}`).value = session.notes?.[card.key] || ''; document.querySelector(`[data-done="${card.key}"]`).checked = Boolean(session.done?.[card.key]); const photo = session.photos?.[card.key]; if(photo?.dataUrl) setPhoto(card.key, photo); });
  updateProgress(); saveSession(false); setStatus('Saved folio restored.');
}

function saveSession(show = true) { localStorage.setItem(MIRROR_FOLIO_STORAGE, JSON.stringify(getSession())); updateProgress(); if(show) setStatus(`Saved ${new Date().toLocaleTimeString()}.`); }
function updateProgress() { const session = getSession(); const completed = FOLIO_CARDS.filter(card => session.done[card.key] || (session.responses[card.key].trim() && session.notes[card.key].trim())).length; $('progressCount').textContent = `${completed} of ${FOLIO_CARDS.length} evidence cards complete`; $('progressBar').style.width = `${completed / FOLIO_CARDS.length * 100}%`; }

function setPhoto(key, photo) { const image = document.querySelector(`[data-preview="${key}"]`); image.src = photo.dataUrl; image.dataset.dataUrl = photo.dataUrl; image.dataset.fileName = photo.name || `${key}.jpg`; image.style.display = 'block'; }
function compressPhoto(file) { return new Promise((resolve,reject) => { const r = new FileReader(); r.onerror = reject; r.onload = () => { const image = new Image(); image.onerror = reject; image.onload = () => { const max = 1400, scale = Math.min(1,max / Math.max(image.width,image.height)); const canvas=document.createElement('canvas'); canvas.width=Math.round(image.width*scale); canvas.height=Math.round(image.height*scale); canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height); resolve({name:file.name.replace(/\.[^.]+$/,'.jpg'),dataUrl:canvas.toDataURL('image/jpeg',.82)}); }; image.src=r.result; }; r.readAsDataURL(file); }); }

function concat(parts) { const length=parts.reduce((total,part)=>total+part.length,0); const result=new Uint8Array(length); let offset=0; parts.forEach(part=>{result.set(part,offset);offset+=part.length;}); return result; }
function crc32(bytes) { let crc=-1; for(let i=0;i<bytes.length;i++){crc^=bytes[i];for(let bit=0;bit<8;bit++)crc=(crc>>>1)^(0xedb88320&-(crc&1));} return (crc^-1)>>>0; }
function u16(out,at,value){out[at]=value&255;out[at+1]=(value>>>8)&255;} function u32(out,at,value){out[at]=value&255;out[at+1]=(value>>>8)&255;out[at+2]=(value>>>16)&255;out[at+3]=(value>>>24)&255;}
function createZip(files) { const local=[], central=[]; let offset=0; const now=new Date(), time=(now.getHours()<<11)|(now.getMinutes()<<5)|Math.floor(now.getSeconds()/2), date=((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate(); files.forEach(file=>{const name=textBytes(file.name), data=file.bytes, crc=crc32(data), head=new Uint8Array(30+name.length);u32(head,0,0x04034b50);u16(head,4,20);u16(head,10,time);u16(head,12,date);u32(head,14,crc);u32(head,18,data.length);u32(head,22,data.length);u16(head,26,name.length);head.set(name,30);local.push(head,data);const entry=new Uint8Array(46+name.length);u32(entry,0,0x02014b50);u16(entry,4,20);u16(entry,6,20);u16(entry,12,time);u16(entry,14,date);u32(entry,16,crc);u32(entry,20,data.length);u32(entry,24,data.length);u16(entry,28,name.length);u32(entry,42,offset);entry.set(name,46);central.push(entry);offset+=head.length+data.length;});const directory=concat(central), end=new Uint8Array(22);u32(end,0,0x06054b50);u16(end,8,files.length);u16(end,10,files.length);u32(end,12,directory.length);u32(end,16,offset);return concat([...local,directory,end]); }
function download(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
function downloadZip() { const session=getSession(), files=[{name:'mirror-project-folio-session.json',bytes:textBytes(JSON.stringify(session,null,2))}]; Object.entries(session.photos).forEach(([key,photo])=>files.push({name:`photos/${key}-${photo.name}`.replace(/[^a-zA-Z0-9._/-]/g,'-'),bytes:dataUrlBytes(photo.dataUrl)})); download(new Blob([createZip(files)],{type:'application/zip'}),`${cleanName(`${session.student.first}-${session.student.last}`)}-mirror-folio-backup.zip`); setStatus('ZIP backup downloaded with answers and photos.'); }
function read16(bytes,at){return bytes[at]|(bytes[at+1]<<8);} function read32(bytes,at){return (bytes[at]|(bytes[at+1]<<8)|(bytes[at+2]<<16)|(bytes[at+3]<<24))>>>0;}
async function restore(file) { try { if(file.name.toLowerCase().endsWith('.json')) { applySession(JSON.parse(await file.text())); return; } const bytes=new Uint8Array(await file.arrayBuffer()); let offset=0, sessionText=''; while(offset<bytes.length&&read32(bytes,offset)===0x04034b50){const method=read16(bytes,offset+8), size=read32(bytes,offset+18), nameSize=read16(bytes,offset+26), extra=read16(bytes,offset+28), start=offset+30+nameSize+extra, name=new TextDecoder().decode(bytes.slice(offset+30,offset+30+nameSize)); if(method!==0) throw new Error('compressed'); if(name==='mirror-project-folio-session.json') sessionText=new TextDecoder().decode(bytes.slice(start,start+size)); offset=start+size;} if(!sessionText) throw new Error('missing'); applySession(JSON.parse(sessionText)); } catch { setStatus('Could not read that backup. Use a ZIP or JSON downloaded from this folio.'); } }
function init() { renderCards(); $('sessionDate').value = new Date().toISOString().slice(0,10); const saved=localStorage.getItem(MIRROR_FOLIO_STORAGE); if(saved){try{applySession(JSON.parse(saved));}catch{localStorage.removeItem(MIRROR_FOLIO_STORAGE);}} updateProgress(); document.addEventListener('input',event=>{if(event.target.matches('input,textarea'))saveSession();}); document.addEventListener('change',async event=>{if(event.target.matches('[data-photo]')){const [file]=event.target.files;if(file){setPhoto(event.target.dataset.photo,await compressPhoto(file));saveSession();}event.target.value='';}else saveSession();}); $('downloadZip').addEventListener('click',downloadZip); $('downloadJson').addEventListener('click',()=>{const session=getSession();download(new Blob([JSON.stringify(session,null,2)],{type:'application/json'}),`${cleanName(`${session.student.first}-${session.student.last}`)}-mirror-folio-session.json`);setStatus('JSON session downloaded.');}); $('restoreSession').addEventListener('click',()=>$('restoreInput').click()); $('restoreInput').addEventListener('change',event=>{const [file]=event.target.files;if(file)restore(file);event.target.value='';}); $('printFolio').addEventListener('click',()=>window.print()); $('clearFolio').addEventListener('click',()=>{if(confirm('Clear all saved Mirror folio work from this browser?')){localStorage.removeItem(MIRROR_FOLIO_STORAGE);location.reload();}}); }
document.addEventListener('DOMContentLoaded',init);
